cookbook/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField, IntegerField
from wtforms.validators import DataRequired, EqualTo, Email, Length, ValidationError, Regexp
from cookbook.models import Users
from flask_login import current_user


class LoginForm(FlaskForm):
    email =  StringField("Email", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    remember = BooleanField("Remember Me", default=False)
    submit = SubmitField("Log in")

class UserRegistrationForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField("Email", validators=[DataRequired(), Email()])
    password_hash = PasswordField('Password', validators=[
        DataRequired(message="Must have a value"),
        Length(min=8, message="At least 8 characters long"),
        Regexp('.*[A-Z].*', message="At least one uppercase letter"),
        Regexp('.*[a-z].*', message="At least one lowercase letter"),
        Regexp('.*[1-9].*', message="At least one number"),
        Regexp('.*[!@#$%^&*()].*', message="At least one special character")
    ], id="password")
    password_hash2 = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password_hash', message="Passwords Must Match!")], id="confirmPassword")
    submit = SubmitField("Sign Up")

    def validate_email(self, email):
        user = Users.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError("Email Already Exists. Please choose another")

class UserUpdateForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField("Email", validators=[DataRequired(), Email()])
    submit = SubmitField("Update")

    def validate_email(self, email):
        # Only run if the data is being updated
        if (email.data != current_user.email):
            user = Users.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError("Email Already Exists. Please choose another")
            
class AdminUserEditForm(FlaskForm):
    id = IntegerField("ID", validators=[DataRequired()])
    name = StringField("Name", validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField("Email", validators=[DataRequired(), Email()])
    submit = SubmitField("Update")

    def validate_email(self, email):
        # Only run if the data is being updated
        if (email.data != current_user.email):
            user = Users.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError("Email Already Exists. Please choose another")

            
class RequestResetForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    submit = SubmitField("Request Password Reset")

    def validate_email(self, email):
        user = Users.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError("Email doesn't exists in the system")

class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[
        DataRequired(message="Must have a value"),
        Length(min=8, message="At least 8 characters long"),
        Regexp('.*[A-Z].*', message='At least one uppercase letter'),
        Regexp('.*[a-z].*', message='At least one lowercase letter'),
        Regexp('.*[1-9].*', message='At least one number'),
        Regexp('.*[!@#$%^&*()].*', message='At least one special character')
    ])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password', message="Passwords Must Match!")])
    submit = SubmitField("Update Password")

cookbook/users/routes.py
from flask import Blueprint, render_template, redirect, flash, url_for, request, session, current_app
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from cookbook.users.forms import LoginForm, UserRegistrationForm, UserUpdateForm, RequestResetForm, ResetPasswordForm, AdminUserEditForm
from cookbook.models import Users, Recipe
from cookbook import db, login_manger
from cookbook.users.utils import logout_required, send_reset_email
from cookbook.users.utils import admin_check
from datetime import timedelta

users = Blueprint('users', __name__)

@login_manger.user_loader
def load_user(user_id):
    return Users.query.get(int(user_id))

@users.route('/login', methods=['GET', 'POST'])
@logout_required
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password_hash, form.password.data):
            # Set the session duration based on the "remember me" checkbox
            if form.remember.data:
                session.permanent = True
                current_app.permanent_session_lifetime = timedelta(weeks=1)
            else:
                session.permanent = False
                current_app.permanent_session_lifetime = timedelta(hours=12)
            login_user(user)
            # If the user tried to access a page that needed login before being able to access
            next_page = request.args.get('next') # this is like args[''] however, if args is empty, instead of an error, it will just return None
            flash("Login Successfull", "success")
            # This is an if statement in one line 
            #       redirect to next_page if exists   else redirect to the home page
            return redirect(next_page) if (next_page) else redirect(url_for('main.home'))
        else:
            flash("Login Unsuccessful. Please check the email and password", "danger")
    return render_template("user/login.html", form=form)

@users.route('/register', methods=['GET', 'POST'])
@logout_required
def register():
    name = None
    form = UserRegistrationForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        if user is None:
            # Hash the password
            hashed_pw = generate_password_hash(form.password_hash.data, "sha256")
            user = Users(name=form.name.data, email=form.email.data, password_hash=hashed_pw)
            db.session.add(user)
            db.session.commit()
        name = form.name.data
        form.name.data = ''
        form.email.data = ''
        form.password_hash.data = ''
        flash("User Added Successfully", "success")
        return redirect(url_for("users.login"))
    return render_template("user/register.html",name=name, form=form)

@users.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    flash("You Have been Logged Out!", "success")
    return redirect(url_for('users.login'))

@users.route('/settings' , methods=['GET', 'POST'])
@login_required
def settings():
    userUpdateForm = UserUpdateForm()
    changePasswordForm = ResetPasswordForm()
    user = Users.query.get_or_404(current_user.id)
    if (userUpdateForm.validate_on_submit()):
        user.name = userUpdateForm.name.data
        user.email = userUpdateForm.email.data
        db.session.commit()
        flash("User Updated", "success")
        return redirect(url_for('users.settings'))
    if (changePasswordForm.validate_on_submit()):
        hashed_pw = generate_password_hash(changePasswordForm.password.data, "sha256")
        user.password_hash = hashed_pw
        db.session.commit()
        flash("Password Updated", "success")
        return redirect(url_for('users.settings'))
    if (request.method == "GET"):
        userUpdateForm.name.data = user.name
        userUpdateForm.email.data = user.email
        return render_template("user/settings.html", userUpdateForm=userUpdateForm, changePasswordForm=changePasswordForm)
    
@users.route('/reset_password', methods=["POST", "GET"])
@logout_required
def reset_request():
    form = RequestResetForm()
    if (current_user.is_authenticated):
        return redirect(url_for('main.home'))
    if (request.method == "POST"):
        user = Users.query.filter_by(email=form.email.data).first()
        if user is None:
            flash("Email doesn't exists in the system", "danger")
            return redirect(url_for('users.reset_request'))
        send_reset_email(user)
        flash("An email has been sent to reset your password", "info")
        return redirect(url_for("users.login"))
    return render_template("user/reset_request.html", title="Reset Password", form=form)

@users.route('/reset_password/<token>', methods=["POST", "GET"])
@logout_required
def reset_token(token):
    if (current_user.is_authenticated):
        return redirect(url_for('main.home'))
    user = Users.verify_reset_token(token)
    if user is None:
        flash("That is an invalid or expired token", "warning")
        return redirect(url_for("users.reset_request"))
    else:
        form = ResetPasswordForm()
        if form.validate_on_submit():
            # Hash the password
            hashed_pw = generate_password_hash(form.password.data, "sha256")
            user.password_hash = hashed_pw
            db.session.commit()
            flash("Your password has been updated!", "success")
            return redirect(url_for("users.login"))
        return render_template("user/reset_token.html", title="Reset Password", form=form)

@users.route('/users/delete_user/<int:id>', methods=['GET', 'DELETE'])
@login_required
def delete_user(id):
    user_to_delete = Users.query.get(id)
    user_admin = Users.query.get(1) # This is a user that gets automatically added when the db is created
    recipes_belonging_to_user = Recipe.query.filter_by(user_id=current_user.id)
    try:
        if (user_to_delete.id == current_user.id):
            for recipe in recipes_belonging_to_user:
                recipe.user = user_admin
            logout_user()
            db.session.delete(user_to_delete)
            db.session.commit()
            flash("User Was Deleted!", "success")
        else:
            flash("You can only delete your own user", "danger")
    except:
        flash("Whoops! There was a problem deleting the user! Try again", "warning")
    finally:
        return redirect(url_for('main.home'))
    
@users.route('/users/admin', methods=['GET'])
@login_required
@admin_check
def admin():
    users = Users.query.all()
    users.pop(0)
    return render_template("user/admin/view_all_users.html", users=users)

@users.route('/users/admin/<int:id>', methods=['GET', 'POST'])            
@login_required
@admin_check
def edit_user(id):
    user_to_edit = Users.query.get(id)
    form = AdminUserEditForm()
    if (request.method == "GET"):
        if (id == 1):
            flash("Not allowed to edit this user details", "warning")
            return redirect(url_for('users.admin'))
        form.id.data = user_to_edit.id
        form.name.data = user_to_edit.name
        form.email.data = user_to_edit.email
        return render_template("user/admin/edit_user.html", user=user_to_edit, form=form)
    
    if (request.method == "POST"):
        user = Users.query.filter_by(id=form.id.data).first()
        if user:
            flash("User already has this id. Choose another one.", "warning")
            return redirect(url_for('users.edit_user', id=id))
        user_to_edit.id = form.id.data
        user_to_edit.name = form.name.data
        user_to_edit.email = form.email.data
        db.session.commit()
        flash("User details updated!", "success")
        return redirect(url_for('users.admin'))

cookbook/templates/user/login.html
{% extends 'base.html' %}

{% block content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/register.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <script src="{{ url_for('static', filename='js/login.js') }}"></script>

    <h1>Login!</h1>
    <br>
    <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
        <form method="post">

            {{ form.hidden_tag() }}

            {{ form.email.label(class="form-label") }}
            {{ form.email(class="form-control") }}
            {% for error in form.email.errors %}
                <span style="color: red;">{{ error }}</span>
            {% endfor %}

            <br>

            <div class="input-container">
                {{ form.password.label(class="form-label") }}
                {{ form.password(class="form-control") }}
                <i class="fa-solid fa-eye" id="eye"></i>
            </div>
            {% for error in form.email.errors %}
                <span style="color: red;">{{ error }}</span>
            {% endfor %}

            <br>

            {{form.remember(class="form-check-input")}}
            {{form.remember.label(class="form-check-label")}}

            <br> <br>
            {{ form.submit(class="btn btn-secondary") }}
        </form>
        <br>
        <small class="text-muted">
            <a class="ml-2" href="{{url_for('users.reset_request')}}">Forgot Password</a>
        </small>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Don't Have An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up</a>
        </small>
    </div>

{% endblock %}

cookbook/templates/user/register.html
{% extends 'base.html' %}

{% block content %}
    <script src="{{ url_for('static', filename='js/password_rules.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/register.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

    <h1>Registration Page</h1>
    <div class="shadow p-3 mb-5 bg-body-tertiary rounded register-div">
        <p>Password Rules:</p>
        <ol>
            {% set i = namespace(value=1) %}
            {% for validator in form.password_hash.validators[1:] %}
              <li id="rule{{i.value}}">{{validator.message}}</li>
              {% set i.value = i.value + 1 %}
            {% endfor %}
        </ol>
        <form class="register-form" method="post">
            <!-- The if statement in each section will display error messages if something goes wrong -->
            {{ form.hidden_tag() }}

            {{ form.name.label(class="form-label") }}
            {% if form.name.errors %}
                {{ form.name(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.name.errors%}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.name(class="form-control") }}
            {% endif %}

            
            {{ form.email.label(class="form-label") }}
            {% if form.email.errors %}
                {{ form.email(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors%}
                        {{ error }}
                    {% endfor %}
                </div>
            {% else %}
                {{ form.email(class="form-control") }}
            {% endif %}
            
            <div class="input-container">
                {{ form.password_hash.label(class="form-label") }}
                {% if form.password_hash.errors %}
                    {{ form.password_hash(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password_hash.errors%}
                            <span>{{ error }}.</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password_hash(class="form-control") }}
                {% endif %}
                <i class="fa-solid fa-eye" id="eye1"></i>
            </div>
            
            <br>

            <div class="input-container">
                {{ form.password_hash2.label(class="form-label") }}
                {% if form.password_hash2.errors %}
                    {{ form.password_hash2(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password_hash2.errors%}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password_hash2(class="form-control") }}
                {% endif %}
                <i class="fa-solid fa-eye" id="eye2"></i>
            </div>
 
            <br>
            {{ form.submit(class="btn btn-secondary") }}
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>

{% endblock %}

cookbook/templates/user/reset_request.html
{% extends 'base.html' %}

{% block content %}

    <h1>Reset Password</h1>
    <br>
    <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
        <form method="post">

            {{ form.hidden_tag() }}

            {{ form.email.label(class="form-label") }}
            {% if form.email.errors %}
                {{ form.email(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors%}
                        {{ error }}
                    {% endfor %}
                </div>
            {% else %}
                {{ form.email(class="form-control") }}
            {% endif %}

            <br>
            {{ form.submit(class="btn btn-secondary") }}
        </form>
        <br>
    </div>

{% endblock %}

cookbook/templates/user/reset_token.html
{% extends 'base.html' %}

{% block content %}
    <script src="{{ url_for('static', filename='js/password_rules.js') }}"></script>
    <h1>Reset Password</h1>
    <br>
    <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
        <p>Password Rules:</p>
        <ol>
            {% set i = namespace(value=1) %}
            {% for validator in form.password.validators[1:] %}
              <li id="rule{{i.value}}">{{validator.message}}</li>
              {% set i.value = i.value + 1 %}
            {% endfor %}
        </ol>
        <form method="post">

            {{ form.hidden_tag() }}

            {{ form.password.label(class="form-label") }}
            {% if form.password.errors %}
                {{ form.password(class="form-control is-invalid", id="password") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors%}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.password(class="form-control", id="password") }}
            {% endif %}

            {{ form.confirm_password.label(class="form-label") }}
            {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors%}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.confirm_password(class="form-control") }}
            {% endif %}   

            <br>
            {{ form.submit(class="btn btn-secondary") }}
        </form>
        <br>
    </div>

{% endblock %}

cookbook/templates/user/settings.html
{% extends 'base.html' %}

{% block content %}
    <script src="{{ url_for('static', filename='js/settings.js') }}"></script>
    <script src="{{ url_for('static', filename='js/password_rules.js') }}"></script>

    <h1>Update User</h1>
    <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
        <legend>User Info</legend>
        <form method="post">
            <!-- The if statement in each section will display error messages if something goes wrong -->
            {{ userUpdateForm.hidden_tag() }}

            {{ userUpdateForm.name.label(class="form-label") }}
            {% if userUpdateForm.name.errors %}
                {{ userUpdateForm.name(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in userUpdateForm.name.errors%}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ userUpdateForm.name(class="form-control") }}
            {% endif %}

            
            {{ userUpdateForm.email.label(class="form-label") }}
            {% if userUpdateForm.email.errors %}
                {{ userUpdateForm.email(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in userUpdateForm.email.errors%}
                        {{ error }}
                    {% endfor %}
                </div>
            {% else %}
                {{ userUpdateForm.email(class="form-control") }}
            {% endif %}


            <br>
            {{ userUpdateForm.submit(class="btn btn-secondary") }}
        </form>
    </div>

    <button class="btn btn-outline-dark" id="change_password_btn" onclick="change_password_form_visibility()">Change Password</button>
    <br> <br>
    <div id="change_password" class="shadow p-3 mb-5 bg-body-tertiary rounded" style="display:none;">
        <legend>Update Password</legend>
        <p>Password Rules:</p>
        <ol>
            {% set i = namespace(value=1) %}
            {% for validator in changePasswordForm.password.validators[1:] %}
              <li id="rule{{i.value}}">{{validator.message}}</li>
              {% set i.value = i.value + 1 %}
            {% endfor %}
        </ol>
        <form method="post">
            {{ changePasswordForm.hidden_tag() }}

            {{ changePasswordForm.password.label(class="form-label") }}
            {% if changePasswordForm.password.errors %}
                {{ changePasswordForm.password(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in changePasswordForm.password.errors%}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ changePasswordForm.password(class="form-control") }}
            {% endif %}

            
            {{ changePasswordForm.confirm_password.label(class="form-label") }}
            {% if changePasswordForm.confirm_password.errors %}
                {{ changePasswordForm.confirm_password(class="form-control is-invalid", id="password") }}
                <div class="invalid-feedback">
                    {% for error in changePasswordForm.confirm_password.errors%}
                        {{ error }}
                    {% endfor %}
                </div>
            {% else %}
                {{ changePasswordForm.confirm_password(class="form-control", id="password") }}
            {% endif %}


            <br>
            {{ changePasswordForm.submit(class="btn btn-secondary") }}
        </form>
    </div>

    <a class="btn btn-danger" href="{{url_for('users.delete_user', id=current_user.id)}}">Delete User</a>

    <!-- <a class="btn btn-danger" id="delete_user_btn">Delete User</a> -->
    <br> <br>

    <!-- <script>
        var deleteBtn = document.getElementById("delete_user_btn");
        deleteBtn.onclick = function() {
          if (confirm("Are you sure you want to delete your account? This action cannot be undone.")) {
            var xhr = new XMLHttpRequest();
            xhr.open("DELETE", "{{ url_for('users.delete_user', id=current_user.id) }}");
            xhr.onreadystatechange = function() {
              if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {
                console.log("user deleted");
                document.location.reload()
              }
              if (this.status === 405) {
                console.error("405");
                document.location.href = "{{url_for('main.home')}}";
              }
            };
            xhr.send();
          }
        };
      </script> -->

{% endblock %}