cookbook/recipes/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FieldList, DecimalField, FormField, SelectField, FileField
from flask_wtf.file import FileAllowed
from wtforms.validators import DataRequired, ValidationError
from cookbook.constants import MEASURING_UNITS

class IngredientsForm(FlaskForm):
    ingredient = StringField("Ingredient", render_kw={"placeholder": "Butter"}, validators=[DataRequired(message="Ingredient can't be empty")])
    amount = DecimalField("Amount", render_kw={"placeholder": "100"}, validators=[DataRequired(message="The ingredient must have an amount")])
    unit = SelectField("Units", choices=MEASURING_UNITS, validators=[DataRequired()])

    def validate_amount_type(self, amount):
        if (not amount.isnumeric()):
            raise ValidationError("Amount must be a number")

class InstructionsForm(FlaskForm):
    instruction = StringField("Instruction", render_kw={"placeholder": "Whip the butter"}, validators=[DataRequired(message="Instruction can't be empty")])

class CategoriesForm(FlaskForm):
    category = StringField("Category", render_kw={"placeholder": "Pastry"}, validators=[DataRequired(message="Cateogry can't be empty")])

class RecipeNameDescImage(FlaskForm):
    name = StringField("Recipe Name", render_kw={"placeholder": "Croissants"}, validators=[DataRequired()])
    description = StringField("Description", render_kw={"placeholder": "A buttery, crescent-shaped French pastry"}, validators=[DataRequired()])
    images = FileField("Image", validators=[FileAllowed(['jpg', 'png', 'jpeg'], "Images Only!")])
    submit = SubmitField("Submit")

class RecipeCategories(FlaskForm):
    categories = FieldList(FormField(CategoriesForm), min_entries=1, validators=[DataRequired()])
    submit = SubmitField("Submit")

class RecipeIngredients(FlaskForm):
    ingredients = FieldList(FormField(IngredientsForm), min_entries=1, validators=[DataRequired()])
    submit = SubmitField("Submit")

class RecipeInstructions(FlaskForm):
    instructions = FieldList(FormField(InstructionsForm), min_entries=1, validators=[DataRequired()])
    submit = SubmitField("Submit")

class RecipeForm(FlaskForm):
    name = StringField("Recipe Name", render_kw={"placeholder": "Croissants"}, validators=[DataRequired()])
    description = StringField("Description", render_kw={"placeholder": "A buttery, crescent-shaped French pastry"}, validators=[DataRequired()])
    images = FileField("Image", validators=[FileAllowed(['jpg', 'png', 'jpeg'], "Images Only!")])
    categories = FieldList(FormField(CategoriesForm), min_entries=1, validators=[DataRequired()])
    ingredients = FieldList(FormField(IngredientsForm), min_entries=1, validators=[DataRequired()])
    instructions = FieldList(FormField(InstructionsForm), min_entries=1, validators=[DataRequired()])
    submit = SubmitField("Submit")

cookbook/recipes/routes.py
from flask import Blueprint, render_template, redirect, flash, url_for, request, session, current_app
from flask_login import login_required, current_user
from cookbook.recipes.forms import RecipeForm, IngredientsForm, InstructionsForm, CategoriesForm, RecipeNameDescImage, RecipeCategories, RecipeIngredients, RecipeInstructions
from cookbook.models import Recipe, Categories, recipe_categories
from cookbook import db
from cookbook.recipes.services import saveRecipe, editRecipe
from cookbook.users.utils import recipe_id_check
from werkzeug.utils import secure_filename
import os
from cookbook.constants import MEASURING_UNITS

recipes = Blueprint('recipes', __name__, url_prefix='/recipes')

@recipes.route('/create_recipe/add_name_and_desc', methods=['GET', 'POST'])
@login_required
def add_name_and_desc():
    form = RecipeForm()
    if request.method == 'POST':
        # Store name and description in one session
        session['recipe_name'] = request.form['name']
        session['recipe_desc'] = request.form['description']

        temp_folder_path = f"{current_app.static_folder}/images/temp"
        if not os.path.exists(temp_folder_path):
            os.makedirs(temp_folder_path)
        # Store the image in a separate session
        file = request.files["images"]
        filename = secure_filename(file.filename)
        if (filename != ""):
            # save the image in a temporary folder so that if something happens, and the user doesn't finish the recipe, the image can be easily deleted later and not saved in the db
            file.save(os.path.join(current_app.static_folder + "/images/temp/", filename))
        session['recipe_image'] = filename

        return redirect(url_for('recipes.add_categories'))
    return render_template('recipe/add_recipe/add_name_and_desc.html', form=form)

@recipes.route('/create_recipe/add_categories', methods=['GET', 'POST'])
@login_required
def add_categories():
    form = RecipeForm()
    if request.method == 'POST':
        session['recipe_categories'] = form.categories.data
        return redirect(url_for('recipes.add_ingredients'))
    return render_template('recipe/add_recipe/add_categories.html', form=form)

@recipes.route('/create_recipe/add_ingredients', methods=['GET', 'POST'])
@login_required
def add_ingredients():
    form = RecipeForm()
    if request.method == 'POST':
        session['recipe_ingredients'] = form.ingredients.data
        return redirect(url_for('recipes.add_instructions'))
    return render_template('recipe/add_recipe/add_ingredients.html', form=form, measuring_units=MEASURING_UNITS)

@recipes.route('/create_recipe/add_instructions', methods=['GET', 'POST'])
@login_required
def add_instructions():
    try:
        form = RecipeForm()
        if request.method == 'POST':
            form = saveRecipe.fillRecipeForm(form)
            # Saving the data in the variable form into the db using the saveRecipe function
            user_id = current_user.id
            recipe = saveRecipe.saveRecipe(form, db, user_id)
            flash('Recipe added successfully', 'success')
            return redirect(url_for('recipes.view_recipe', id=recipe.id))
        return render_template('recipe/add_recipe/add_instructions.html', form=form)
    except Exception as e:
        current_app.logger.error(e)
        return render_template("recipe/add_recipe/add_instructions.html", form=form, exception=e)
    

@recipes.route('/view_recipe/<int:id>')
def view_recipe(id):
    recipe = Recipe.query.get_or_404(id)
    return render_template("recipe/view_recipe.html", recipe=recipe)


@recipes.route('/edit_recipe/edit_name_and_desc/<int:id>', methods=['GET', 'POST'])
@login_required
@recipe_id_check(msg="edit", type="warning")
def edit_name_and_desc(id):
    recipe = Recipe.query.get_or_404(id)
    form = RecipeNameDescImage()
    if form.validate_on_submit():
        # Save the form data to the session
        session['recipe_name'] = request.form['name']
        session['recipe_desc'] = request.form['description']

        temp_folder_path = f"{current_app.static_folder}/images/temp"
        if not os.path.exists(temp_folder_path):
            os.makedirs(temp_folder_path)
        # save the image to a temp folder, and in teh session save the image name
        file = request.files["images"]
        filename = secure_filename(file.filename)
        # Run only if there is an acutal image uploaded
        if (filename != ""):
            # save the image in a temporary folder so that if something happens, and the user doesn't finish the recipe, the image can be easily deleted later and not saved in the db
            file.save(os.path.join(current_app.static_folder + "/images/temp/", filename))
        session['recipe_image'] = filename

        # Redirect to the next page
        return redirect(url_for('recipes.edit_categories', id=recipe.id))
    else: # view the page OR if something went wrong with the form validation
        # Display the form with existing data
        form.name.data = recipe.name
        form.description.data = recipe.description
        return render_template("recipe/edit_recipe/edit_name_and_desc.html", form=form)


@recipes.route('/edit_recipe/edit_categories/<int:id>', methods=['GET', 'POST'])
@login_required
@recipe_id_check(msg="edit", type="warning")
def edit_categories(id):
    recipe = Recipe.query.get_or_404(id)
    form = RecipeCategories()
    if form.validate_on_submit():      
        session['recipe_categories'] = form.categories.data
        return redirect(url_for('recipes.edit_ingredients', id=recipe.id))
    else: # view the page OR if something went wrong with the form validation
        categories_forms = []
        for entry in recipe.categories:
            categories_forms.append(CategoriesForm(category=entry.name))
        form.categories = categories_forms
        return render_template("recipe/edit_recipe/edit_categories.html", form=form)


@recipes.route('/edit_recipe/edit_ingredients/<int:id>', methods=['GET', 'POST'])
@login_required
@recipe_id_check(msg="edit", type="warning")
def edit_ingredients(id):
    recipe = Recipe.query.get_or_404(id)
    form = RecipeIngredients()
    if form.validate_on_submit():
        session['recipe_ingredients'] = form.ingredients.data
        return redirect(url_for('recipes.edit_instructions', id=recipe.id))
    else: # view the page OR if something went wrong with the form validation
        current_app.logger.error(form.ingredients.errors)
        ingredients_forms = []
        for entry in recipe.recipe_ingredients:
            ingredients_forms.append(IngredientsForm(ingredient=entry.ingredient, amount=entry.amount, unit=entry.unit))
        form.ingredients = ingredients_forms
        return render_template("recipe/edit_recipe/edit_ingredients.html", form=form, measuring_units=MEASURING_UNITS)


@recipes.route('/edit_recipe/edit_instructions/<int:id>', methods=['GET', 'POST'])
@login_required
@recipe_id_check(msg="edit", type="warning")
def edit_instructions(id):
    recipe = Recipe.query.get_or_404(id)
    form = RecipeInstructions()
    recipeForm = RecipeForm()
    if form.validate_on_submit():
        session['recipe_intructions'] = form.instructions.data
        recipeForm = editRecipe.fillRecipeForm(recipeForm)
        recipe = editRecipe.editRecipe(recipe, recipeForm, db)
        flash("Recipe has been updated", "success")
        return redirect(url_for('recipes.view_recipe', id=recipe.id))
    else: # view the page OR if something went wrong with the form validation
        instructions_forms = []
        for entry in recipe.recipe_instructions:
            instructions_forms.append(InstructionsForm(instruction=entry.instruction))
        form.instructions = instructions_forms
        return render_template("recipe/edit_recipe/edit_instructions.html", form=form)

@recipes.route('/delete_recipe/<int:id>', methods=['GET', 'POST'])
@login_required
@recipe_id_check(msg="delete", type="warning")
def delete_recipe(id):
    recipe_to_delete = Recipe.query.get_or_404(id)
    try:
        db.session.delete(recipe_to_delete)
        db.session.commit()
        flash("Recipe Was Deleted!", "success")
    except:
        flash("Whoops! There was a problem deleting the recipe! Try again", "warning")
    finally:
        return redirect(url_for("main.home"))
    
@recipes.route('/view_my_recipes')
@login_required
def view_my_recipes():
    page = request.args.get('page', default=1, type=int)
    recipes = Recipe.query.filter_by(user_id=current_user.id).order_by(Recipe.date_added.desc()).paginate(page=page, per_page=2)

    return render_template("recipe/view_my_recipes.html", recipes=recipes)

@recipes.route('/view_recipes_by_category/<name>')
def view_recipes_by_category(name):
    recipes = Recipe.query.join(recipe_categories).join(Categories).filter(Categories.name == name).all()

    return render_template("recipe/view_recipes_by_category.html", recipes=recipes, category=name)

cookbook/templates/recipe/recipe_card.html
<link rel="stylesheet" href="{{ url_for('static', filename='css/recipe_card.css') }}">
<script src="{{ url_for('static', filename='js/recipe_card.js') }}"></script>


<div class="recipe_card shadow p-5 mb-5 bg-body-tertiary rounded">
    <div class="right">
        <a class="btn btn-secondary" href="{{url_for('recipes.view_recipe', id=recipe.id)}}">View Recipe</a>
        {% if current_user.id == recipe.user_id %}
            <a class="btn btn-secondary" href="{{url_for('recipes.edit_name_and_desc', id=recipe.id)}}">Edit Recipe</a>
        {% endif %}

        {% if current_user.id == recipe.user_id %}
            <div class="delete">
                <a class="btn btn-danger" href="{{url_for('recipes.delete_recipe', id=recipe.id)}}">Delete Recipe</a>
            </div>
        {% endif %}
    </div>
    <div class="left">
        <h2>{{recipe.name|capitalize}}</h2>
        <p><strong>Author:</strong> {{recipe.user.name|capitalize}}</p>
        <p><strong>Description:</strong> {{recipe.description|capitalize}}</p>
        <p>
            <strong>Categories:</strong>
            {% for category in recipe.categories %}
                <a href="{{url_for('recipes.view_recipes_by_category', name=category.name)}}">{{category.name|capitalize}}</a>{% if not loop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p><strong>Date Added:</strong> {{recipe.date_added.strftime('%d/%m/%Y')}}</p>
    </div>

    <div class="right">
        {% for image in recipe.recipe_images %}
            <div class="image-container">
                <img class="recipe_card" src="{{url_for('static', filename='images/recipes/' + image.image)}}"  onclick="enlargeImage(this)">
            </div>
        {% endfor %}
    </div>
    <br>

</div>

cookbook/templates/recipe/view_my_recipes.html
{% extends 'base.html' %}

{% block content %}

    <h1>My Recipes</h1>
    {% if recipes.total == 0 %}
        <h4> {{ current_user.name|capitalize }} has no recipes</h4>
    {% elif recipes.total == 1 %}
        <h4> {{ current_user.name|capitalize }} has 1 recipe</h4>
    {% else %}
        <h4> {{ current_user.name|capitalize }} has {{ recipes.total  }} recipes</h4>
    {% endif %}
    
    {% for recipe in recipes.items %}
        {% include 'recipe/recipe_card.html' %}
    {% endfor %}

    {% for page_num in recipes.iter_pages() %}
        {% if page_num %}
            {% if recipes.page == page_num %}
                <a class="btn btn-secondary mb-4" href="{{ url_for('recipes.view_my_recipes', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-secondary mb-4" href="{{ url_for('recipes.view_my_recipes', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}


{% endblock %}

cookbook/templates/recipe/view_recipe.html
{% extends 'base.html' %}

{% block content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/recipe_card.css') }}">
    <script src="{{ url_for('static', filename='js/recipe_card.js') }}"></script>

    <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
        {% if current_user.id == recipe.user_id %}
            <div class="right">
                <a class="btn btn-secondary" href="{{url_for('recipes.edit_name_and_desc', id=recipe.id)}}">Edit Recipe</a>
                <a class="btn btn-danger" href="{{url_for('recipes.delete_recipe', id=recipe.id)}}">Delete Recipe</a>
            </div>
        {% endif %}
        <h2>{{recipe.name|capitalize}}</h2>
        <p><strong>Description:</strong> {{recipe.description|capitalize}}</p>
        <br>
        <div class="ingredient-container">
            <p><strong>Ingridients:</strong>
                <br>
                {% set count = namespace(value=1) %}
                {% for ingredient in recipe.recipe_ingredients %}
                    <p><strong>{{ count.value }})</strong> {{ingredient.amount}}  {{ingredient.unit}}  - {{ingredient.ingredient|capitalize}}</p>
                    {% set count.value = count.value + 1 %}
                {% endfor %}
        </div>
        
        <br>
        <p><strong>Instructions:</strong>
        {% for instruction in recipe.recipe_instructions %}
            <p><strong>{{ instruction.instruction_number }})</strong> {{instruction.instruction|capitalize}}</p>
            {% set count.value = count.value + 1 %}
        {% endfor %}
        
        <div class="right view_image">
            {% for image in recipe.recipe_images %}
                <div class="image-container">
                    <img class="recipe_card" src="{{url_for('static', filename='images/recipes/' + image.image)}}"  onclick="enlargeImage(this)">
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

cookbook/templates/recipe/view_recipes_by_category.html
{% extends 'base.html' %}

{% block content %}

    <h1>My Recipes</h1>

    <h3><u>{{category|capitalize}}</u></h3>

    {% if recipes %}
        {% for recipe in recipes %}
            {% include 'recipe/recipe_card.html' %}
        {% endfor %}
    {% else %}
        <p>{{category|capitalize}} has no recipes</p>
    {% endif %}

{% endblock %}